services:
  dbrpc:
    command:
      - --bind-host
      - 0.0.0.0
      - --bind-port
      - '8079'
      - --db-host
      - redis
      - --db-port
      - '6379'
      - --secret
      - I_am_an_unsafe_secret
    image: gcr.io/ramaro-dev/aaaas-dbrpc:0.1
    ports:
      - 8079:8079
version: '3'
