apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    chart: redis-10.3.4
    heritage: Tiller
    release: prod
  name: prod-redis-headless
spec:
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    app: redis
    release: prod
  type: ClusterIP
