apiVersion: v1
data:
  ping_liveness_local.sh: "response=$(\n  timeout -s 9 $1 \\\n  redis-cli \\\n   \
    \ -a $REDIS_PASSWORD --no-auth-warning \\\n    -h localhost \\\n    -p $REDIS_PORT\
    \ \\\n    ping\n)\nif [ \"$response\" != \"PONG\" ] && [ \"$response\" != \"LOADING\
    \ Redis is loading the dataset in memory\" ]; then\n  echo \"$response\"\n  exit\
    \ 1\nfi"
  ping_liveness_local_and_master.sh: 'script_dir="$(dirname "$0")"

    exit_status=0

    "$script_dir/ping_liveness_local.sh" $1 || exit_status=$?

    "$script_dir/ping_liveness_master.sh" $1 || exit_status=$?

    exit $exit_status'
  ping_liveness_master.sh: "response=$(\n  timeout -s 9 $1 \\\n  redis-cli \\\n  \
    \  -a $REDIS_MASTER_PASSWORD --no-auth-warning \\\n    -h $REDIS_MASTER_HOST \\\
    \n    -p $REDIS_MASTER_PORT_NUMBER \\\n    ping\n)\nif [ \"$response\" != \"PONG\"\
    \ ] && [ \"$response\" != \"LOADING Redis is loading the dataset in memory\" ];\
    \ then\n  echo \"$response\"\n  exit 1\nfi"
  ping_readiness_local.sh: "response=$(\n  timeout -s 9 $1 \\\n  redis-cli \\\n  \
    \  -a $REDIS_PASSWORD --no-auth-warning \\\n    -h localhost \\\n    -p $REDIS_PORT\
    \ \\\n    ping\n)\nif [ \"$response\" != \"PONG\" ]; then\n  echo \"$response\"\
    \n  exit 1\nfi"
  ping_readiness_local_and_master.sh: 'script_dir="$(dirname "$0")"

    exit_status=0

    "$script_dir/ping_readiness_local.sh" $1 || exit_status=$?

    "$script_dir/ping_readiness_master.sh" $1 || exit_status=$?

    exit $exit_status'
  ping_readiness_master.sh: "response=$(\n  timeout -s 9 $1 \\\n  redis-cli \\\n \
    \   -a $REDIS_MASTER_PASSWORD --no-auth-warning \\\n    -h $REDIS_MASTER_HOST\
    \ \\\n    -p $REDIS_MASTER_PORT_NUMBER \\\n    ping\n)\nif [ \"$response\" !=\
    \ \"PONG\" ]; then\n  echo \"$response\"\n  exit 1\nfi"
kind: ConfigMap
metadata:
  labels:
    app: redis
    chart: redis-10.3.4
    heritage: Tiller
    release: prod
  name: prod-redis-health
