parameters:
  redis:
    _compile:
      kubernetes:
        - output_path: manifests_helm
          input_type: helm
          input_paths:
            - components/redis/chart
          helm_params:
            release_name: ${target}
            namespace: ${target}
          helm_values:
            redisPort: ${redis:bind_port}
            usePassword: false
            cluster:
              enabled: false
            master:
              persistence:
                enabled: false
              livenessPRobe:
                enabled: false
              readinessProbe:
                enbabled: false

    _dependencies:
      kubernetes:
        - type: git
          output_path: components/redis/chart
          source: git@github.com:helm/charts.git
          subdir: stable/redis
          ref: 69ef199
      compose: []
