classes:
  - component.redis.helm

parameters:
  redis:
    image: redis:5.0.7
    bind_port: 6379

    args:
      - --port
      - ${redis:bind_port}

  kapitan:
    redis:
      _compile:
        compose:
          - output_path: manifests
            input_type: jsonnet
            input_paths:
              - components/redis/main.jsonnet
            output_type: yaml

      _dependencies:
        compose: []

    compile: ${kapitan:redis:_compile:${platform}}
    dependencies: ${kapitan:redis:_dependencies:${platform}}
