#!/usr/bin/env bash
set -e

DIR=$(dirname ${BASH_SOURCE[0]})


gcloud container clusters get-credentials ramaro-dev --zone europe-west2-c --project ramaro-dev &> /dev/null

for file in ${DIR}/../manifests/*.yml
do
    kubectl apply -f ${file}
done

for file in $(find ${DIR}/../manifests_helm/ -name '*.y*ml')
do
    kubectl -n prod apply -f ${file}
done
