#!/usr/bin/env bash
set -e

{% set i = inventory.parameters %}
{% set platform = i.platform %}

DIR=$(dirname ${BASH_SOURCE[0]})

{% if platform == "compose" %}
COMPOSE_ARGS=""
for file in ${DIR}/../manifests/*.yml
do
    COMPOSE_ARGS="${COMPOSE_ARGS} -f ${file}"
done

docker-compose ${COMPOSE_ARGS} $@
{% endif %}

{% if platform == "kubernetes" %}
gcloud container clusters get-credentials {{i.kubernetes.cluster}} --zone {{i.kubernetes.zone}} --project {{i.kubernetes.project}} &> /dev/null

kubectl -n {{i.target}} $@
{% endif %}
