#!/usr/bin/env bash
set -e

{% set i = inventory.parameters %}
{% set platform = i.platform %}
DIR=$(dirname ${BASH_SOURCE[0]})

{% if platform == "compose" %}
COMPOSE_ARGS=""
for file in ${DIR}/../manifests/*.yml
do
    COMPOSE_ARGS="${COMPOSE_ARGS} -f ${file}"
done

docker-compose ${COMPOSE_ARGS} up -d
{% endif %}

{% if platform == "kubernetes" %}
gcloud container clusters get-credentials {{i.kubernetes.cluster}} --zone {{i.kubernetes.zone}} --project {{i.kubernetes.project}} &> /dev/null

for file in ${DIR}/../manifests/*.yml
do
    kubectl apply -f ${file}
done

for file in $(find ${DIR}/../manifests_helm/ -name '*.y*ml')
do
    kubectl -n {{i.target}} apply -f ${file}
done
{% endif %}
