apiVersion: v1
kind: Service
metadata:
  labels:
    name: api
  name: api
  namespace: prod
spec:
  ports:
    - name: http
      nodePort: 30080
      port: 8080
      targetPort: 8080
  selector:
    app: api
  type: NodePort
