apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - args:
            - --bind-host
            - 0.0.0.0
            - --bind-port
            - '8080'
            - --dbrpc-host
            - dbrpc
            - --dbrpc-port
            - '8079'
            - --dbrpc-secret
            - I_am_an_unsafe_secret
          image: gcr.io/ramaro-dev/aaaas-api:0.1
          imagePullPolicy: Always
          name: api
          ports:
            - containerPort: 8080
