apiVersion: v1
kind: Service
metadata:
  labels:
    name: dbrpc
  name: dbrpc
  namespace: prod
spec:
  ports:
    - name: http
      port: 8079
      targetPort: 8079
  selector:
    app: dbrpc
  type: ClusterIP
