#!/usr/bin/env bash
set -e

DIR=$(dirname ${BASH_SOURCE[0]})

COMPOSE_ARGS=""
for file in ${DIR}/../manifests/*.yml
do
    COMPOSE_ARGS="${COMPOSE_ARGS} -f ${file}"
done

docker-compose ${COMPOSE_ARGS} ps

