#!/usr/bin/env bash
set -e

{% set i = inventory.parameters %}
{% set platform = i.platform %}

DIR=$(dirname ${BASH_SOURCE[0]})

{% if platform == "compose" %}
COMPOSE_ARGS=""
for file in ${DIR}/../manifests/compose*.yml
do
    COMPOSE_ARGS="${COMPOSE_ARGS} -f ${file}"
done
{% endif %}

docker-compose ${COMPOSE_ARGS} down
