classes:
  - service.gkms #default KMS key for kubernetes targets

parameters:
  platform: kubernetes
  url: https://demo.ramaro.dev
  kubernetes:
    project: ramaro-dev
    zone: europe-west2-c
    cluster: ramaro-dev

  kapitan:
    compile:
    # always create namespace per target
      - output_path: manifests
        input_type: jsonnet
        input_paths:
          - components/namespace/main.jsonnet
        output_type: yaml
